### ISSUE TITLE
Support for different output formats

### ISSUE THREAD

**Issue by offlinehacker** [RaiMan/SikuliX-2014#104]
Currently scripts can only be exported as python, it would be nice if there would be a machine parsable format. Something similar a selenium ide does.

**Comment by RaiMan** [comment]
Not really sure what you mean with "exported as"

With SikuliX you have to options with scripting:
-- 1: use the SikuliX IDE. Then you can use either Python or Ruby language for scripting, since these 2 interpreters (Jython and/or JRuby) can be bundled with the IDE (sikulix.jar with 1.1.0)
-- 2: use any IDE environment with any scripting language that either directly or indirectly (via some bridging/binding libraries) allow to use compiled Java classes usually packaged in jars (with version 1.1.0 you would use sikulixapi.jar). The runtime support for scripting in this case has to be setup by yourself.

As far as I understand the Selenium IDE, then it uses some DSL, that can be exported to different scripting languages or even Java code.

So final question: what do you mean with: machine parsable format?
