### ISSUE TITLE
What is the most stable 1.1 nightly?  Or should I wait until the next nightly that is upcoming?

### ISSUE THREAD

**Issue by tmairegasnighto** [RaiMan/SikuliX-2014#108]
I have an important project that I want to start automating.  It doesn't need to be polished, but it does need to be functional.  Rather than use 1.0.1, I'd rather have something with the 1.1 bells and whistles so that updating to the final 1.1 isn't much change when the dev is complete.

Should I take one of the Jan nightlies or wait for an uncoming nightly?

**Comment by RaiMan** [comment]
The right nightly is always the one available (there are no historic versions - only one at time)
If yo can wait a few days: after 5 weeks there will be a recent nightly.

But nothing speaks against just starting with the Jan-16 (the currently latest) version to get familiar with everything.
With usage patterns and API it is stable.

**Comment by tmairegasnighto** [comment]
What's going to be in this next nightly?  Has anyone else been using it - or only yourself?

**Comment by RaiMan** [comment]
definitely 3 others (testing specific things) and myself on Mac, Windows and Linux.

there are about 100 forks on GiHub, where I do not know, what they are doing.

But again: start with the available nightly TODAY or do not do it at all.

The next nightly will not be more stable than the current one.

Running on Mac and Window is rather safe, other Linux than current Ubuntu (and other Debian derivates) are risky anyways.

BTW: looking from the standpoint of a professional developer or tester SikuliX is risky anyways, since it is still not tested seriously and completely.
So if you use it for very important projects and/or projects with a strict timeline, you should be very careful, though the core features have a short learning curve. 

If you tell me a bit more about your project, may be I can give you a better suggestion (system(s), web app or not, strict GUI, ....)

Raimund

**Comment by tmairegasnighto** [comment]
I run the month-end accounting for a company.  It requires me to log into several Microsoft Terminal servers, AS400 terminals, and finally run some old custom windows programs.  With all the remote connections, there is no other automation software that can handle it.

There are a few things to run each night, and then a TON of stuff to do on the day after the last day of the month.

I was hoping to quickly write something to test this weekend since the next two month-ends fall mid-week.  So if I don't automate it today, it won't be until June.

In any case, I'll be watching it, so if it fails, I'll just take over manually.  If it works, it is a big deal for our company which has many people doing many many things every month-end.  Like thousands of man hours saved.

**Comment by RaiMan** [comment]
be assured again:
what you now start with the 1.1.0 nightly from Jan-16 will work with any 1.1.0 version later.
The earlier you start, the more questions you can ask ;-)
