### ISSUE TITLE
[Fixed] JRuby: observer callbacks not working with sikulixapi.jar (sikulix.jar must be on class path)

### ISSUE THREAD

**Issue by rstormsf** [RaiMan/SikuliX-2014#113]
not sure what I am doing wrong

```
java/util/Formatter.java:2519:in `format': java.util.MissingFormatArgumentException: Format specifier '%s'
	from java/util/Formatter.java:2455:in `format'
	from java/lang/String.java:2927:in `format'
	from org/sikuli/basics/Debug.java:680:in `log'
	from org/sikuli/basics/Debug.java:586:in `error'
	from org/sikuli/script/ObserverCallBack.java:63:in `<init>'
	from org/sikuli/script/Region.java:2864:in `onEvent'
	from org/sikuli/script/Region.java:2846:in `onAppear'
	from java/lang/reflect/Method.java:483:in `invoke'
	from ~/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/sikulix-1.1.0.3/lib/sikulix/sikulix.rb:115:in `onAppear'
	from test.rb:18:in `(root)'
	from test.rb:18:in `(root)'
```

running this one
https://github.com/RaiMan/SikuliX-2014/blob/25745bd317fa10bf2dfe0e930857e608d6eb2a9b/StuffContainer/testScripts/testObserve/testJRubyRegion.sikuli/testJRubyRegion.rb

**Comment by rssdev10** [comment]
sikulix.gem on rubygems.org has not updated. Version 1.1.0.3 does not correspond to current code of sikulix-api.jar
Either replace ~/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/sikulix-1.1.0.3/lib/sikulix/sikulix.rb by https://github.com/RaiMan/SikuliX-2014/blob/master/JRubyGem/lib/sikulix/sikulix.rb manually or wait updated gem.

@RaiMan I guess it is required a check of sikulix_api.jar version (by data, by major version or other) in https://github.com/RaiMan/SikuliX-2014/blob/master/JRubyGem/lib/sikulix/platform.rb and an appropriate message in case of incompatibility.

**Comment by RaiMan** [comment]
Sorry, but I just did not have an eye on the gem the last weeks (have to admit: not my priority).

... and I have to admit, that I do not understand the problem (... and do not have the time currently to dive into).

So any help would be appreciated.

**Comment by rstormsf** [comment]
@rssdev10 replacing `sikulix.rb` to the latest code - didn't help.

looks like there is some missing parameter 
```
java.util.MissingFormatArgumentException: Format specifier '%s'
```
for `onAppear` callback. Since it calls Java Method, the issue shouldn't be related to rubygem.

**Comment by RaiMan** [comment]
I fixed the java.util.MissingFormatArgumentException.
But this is only the top of the problem.
The intended error message would have read:
ObserverCallBack: APPEAR init: ScriptRunner not available for jruby" 

... and hence does not run anyway in the moment in the gem version with 1.1.0.

(the reason behind: I moved the callback handling completely to the Java level using reflection. This working for Jython even in the setup with sikulixapi.jar and external Jython. But for JRuby currently only the setup with the IDE jar (sikulix.jar) works, since the JRuby support still relies on the support of class ScriptRunner in the IDE package).

I have to revise that the next days.

So you have to use 1.0.1 for the moment.

**Comment by rstormsf** [comment]
I see. Thanks for explanation. I should probably switch to Python version.

**Comment by RaiMan** [comment]
If Ruby is not a must: yes

**Comment by RaiMan** [comment]
works with 1.1.0 final

**Comment by RaiMan** [comment]
fixed thanks to https://github.com/RaiMan/SikuliX-2014/pull/191
