### ISSUE TITLE
Using nightly builds setup.  Image: could not be loaded:.png

### ISSUE THREAD

**Issue by rstormsf** [RaiMan/SikuliX-2014#118]
No idea where it tries to load such file
[error] Image: could not be loaded: file:/Users/USERNAME/repos/sikuli0jython/test.sikuli/.png
[error] Image: Image not valid, but TextSearch is switched off!

**Comment by rstormsf** [comment]
How to FULLY clean up Mac environment to FULLY uninstall sikulix
I've noticed that when I try to open new SikuliIDE it remembers the last project that I opened. 
Where does it get this information from?

**Comment by rstormsf** [comment]
something wrong going on. I wish there was more build history on nightly builds. to rollback to previous verisons

**Comment by rstormsf** [comment]
Also, could you point to the right direction on how to use Python sikuli since Ruby is not really supported.
https://github.com/RaiMan/SikuliX-2014/wiki/Usage-in-Java-programming
here when I try to 
```
import org.sikuli.basics.SikulixForJython
from sikuli import *
```
it just can't find it.
What should I do in order to load the library for Jython env?

**Comment by RaiMan** [comment]
As mentioned on the nightly page:
The manually downloaded stuff (sikulixapi-1.1.0-20150325.143910-76.jar and sikulixlibsmac-1.1.0-20150325.143602-89.jar in your case) is not useable as such.
It MUST be processed by sikulixsetup to get a useable sikulixapi.jar, which on top has the advantage to be a stable name to reference.

… and it is also stated:  
-- run in a way, that your current installation and your work is safe or can be restored

So if you backup the last running version of sikulixapi.jar, you can always restore it, if needed.

So do me a favor and run setup in the intended way and use sikulixapi.jar instead of you 2-classpath-entry-hack.

On Mac, the session persistence store is in
~/Library/Preferences/org.sikuli……plist

Purging this file and the respective .lockfile will reset the session store.

**Comment by rstormsf** [comment]
awesome! I don't know whatever I was thinking yesterday. Now everything works as expected.
Downloaded [this](https://oss.sonatype.org/content/groups/public/com/sikulix/sikulixsetup/1.1.0-SNAPSHOT/sikulixsetup-1.1.0-20150326.000959-14-forsetup.jar) nightly build, removed all `CLASSPATH`s, ran setup, exported `sikulixapi.jar` into `zshrc` 
Opened SikulixIDE - works fine.
tried to run as `jython` script - works fine with both as `sys.path.append('sikulixapi.jar')` OR 
`load('sikulixapi.jar')` 
it shows some error when I use it with `load`, but still works 
```
[error] JythonSupport: load: could not be found - even not in bundle nor in extensions
```

here is my final script with MongoDB connection.

```
import org.sikuli.basics.SikulixForJython
from sikuli import *

load("mongo-java-driver-3.0.0-rc1.jar")
from com.mongodb import *
load('sikulixapi.jar')

click("1427427184393.png")

m = MongoClient("localhost")
db = m.getDB("test")
coll = db.getCollection("accounts")
a = coll.findOne()
print a
```
everything works! Thank you Mr. @RaiMan

**Comment by rstormsf** [comment]
Ran the same code on windows, got this one:
```
[error] RunTimeINIT:  *** terminating: no valid Java context for SikuliX available (java.security.CodeSource.getLocation() is null)
```

**Comment by RaiMan** [comment]
```
load('sikulixapi.jar')
import org.sikuli.basics.SikulixForJython
from sikuli import *
```
... does not make sense, since load() is only available after from sikuli import *, since it is a SikuliX feature.

sikulixapi.jar ALWAYS must be on Java class path. How to add it there depends on the way you start Jython. usually one adds CLASSPATH=.... to the system environment some how (static or dynamic).

so according to
https://github.com/RaiMan/SikuliX-2014/wiki/Usage-in-Java-programming

this is valid:
- take care, that sikulixapi.jar is on the Java class path before starting Jython
- in your script at the beginning before using any SikuliX features add
```
import org.sikuli.basics.SikulixForJython
from sikuli import *
```

The first import checks the environment for some aspects important for SikuliX and adds sikulixapi.jar/Lib to the python path (sys.path).
The second import adds many SikuliX methods and classes (Java and Python) to the global namespace and does some initialization for the Jython environment.

**Comment by rstormsf** [comment]
Now it worked! I thought I could just add `jar` dynamically, now when I setup my CLASSPATH to the `sikulixapi.jar`, ran the script - all is fine.
Thank you again @RaiMan

**Comment by RaiMan** [comment]
Thanks for confirmation. all the best.

--- I thought I could just add jar dynamically
Yep, that is the story of the still open question:
What was first: the chicken or the egg???
