### ISSUE TITLE
Provide standalone download

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#124]
Hi RaiMan,

Is it possible to provide a simple "unpack and run" download for offline usage?

**Comment by RaiMan** [comment]
possible? of course ;-) 

.... but ;-)

The setup with the final 1.1.x will be a bit easier to handle than the current nightly builds, but there will always be a setup with this version:
 - there are 3 system variants (Windows, Mac and Linux)
 - there are 2 usage variants (IDE and API)
 - for the mostly used Jython scripting, there are 2 variants (Java 6 and Java 7+)
 - then we have the Ruby option
 - then we have the bundled Tesseract option

I have already stripped down the variants and needed packages and the setup now runs rather reliably (online or offline). for offline setup it is clearly stated, what you have to download for what.

Since the setup is needed anyway to build these "unpack and run" packages, the difference currently is, that only the build and upload of the base packs runs on my private Jenkins server and the user has to do the rest. But I do not really see the problem.

Later this year with a 1.1.x we will probably have an "unpack and run" for the IDE for Windows (.exe) and Mac (.app) and probably an option to let these packages spit out a ready-to-use sikulixapi.jar.
For Linux the situation will always be different, since there we need some prerequisites, that cannot be bundled, since they are linux flavour specific.

But feel free, to make any suggestions, that would make it possible, to get what you want in a way, that works fully automatic and can be run on my Jenkins server or on any "build-and-deploy" service available in the net.
