### ISSUE TITLE
Sikulix IDE can't load external jars (mongodb)

### ISSUE THREAD

**Issue by rstormsf** [RaiMan/SikuliX-2014#129]
If I run a script using command line like this:

```
import sys
import os
import subprocess

import org.sikuli.basics.SikulixForJython
from sikuli import *
load('sikulixapi.jar')
load("mongo-java-driver-3.0.0-rc1.jar")
ImagePath.add("C:\\sikulix\\test.sikuli\\.")
from com.mongodb import *
from com.mongodb.client.model import *
from org.bson import *

# Debug.setDebugLevel(3)
m = MongoClient("10.0.3.2")
db = m.getDatabase("test")
coll = db.getCollection("accounts")

user = coll.find(Filters.and(Filters.exists("ImageUrl"), Filters.exists("snapshot"))).first()
print user.toJson()

click("1429755112591.png")


click("1429755196737.png")

```

using command line - it works fine.
I put mongo-java -driver in Lib and Extenstions folder - works fine!
BUT
when I open it in Sikulix IDE - it cna't find that jar, hence throws me an error.

**BUG#2**
Little bug I noticed using command line: if jar can't be found error message shows twice:
`[error] JythonSupport: load: could not be found - even not in bundle nor in Lib nor in Extensions`
if jar exists and works fine, 1 error line shows anyways, I guess there is some duplication going on somewhere

**Comment by RaiMan** [comment]
I made some tests.

your code can be stripped down so:

```
# sys and os are already imported by sikuli import *
import subprocess

import org.sikuli.script.SikulixForJython # with 1.1.0+
from sikuli import *
# load('sikulixapi.jar') # this is already loaded and on class and python path
load("mongo-java-driver-3.0.0-rc1.jar")
ImagePath.add("C:\\sikulix\\test.sikuli\\.")
from com.mongodb import *
from com.mongodb.client.model import *
from org.bson import *
```
I was not able to import anything from the mongodb.jar, since with every variant some Java classes where missing.
e.g. with from com.mongodb import *
java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: com/mongodb/ReadPreference
(I looked into the jar: a class ReadPreference in fact does not exists)
I another test variant it got obvious, that the complete connection.* branch is missing.

when running this in the IDE, this internal import error is wrapped and finally reported as ImportError-module-not-found (which indeed is irritating - I put it on the list, to change the behaviour)

I tested the import with my own jar and this worked in all situations.

Anyway: be sure to use the same latest version in all these different scenarios.

**Comment by RaiMan** [comment]
no more activities
