### ISSUE TITLE
Typing text is scrambled

### ISSUE THREAD

**Issue by programmin1** [RaiMan/SikuliX-2014#203]
Apparently since Mac OS 10.11.4 typing text from Sikuli 1.1 gets scrambled.

I'm using it to open the keychain, then go 

```
type("f", KeyModifier.CMD + KeyModifier.ALT)
type(shortidentifier)
```

The short identifier is not found anymore because typing gets scrambled, types letters in the wrong order.

**Comment by RaiMan** [comment]
I could reproduce your problem on my MacBookPro same OSX.
In about 7 of 10 types one character was out of sequence.
Apparently the behavior of the search field has changed.

As always in such situations inserting short wait()s make things more robust.

```
type("f", KeyModifier.CMD + KeyModifier.ALT); wait(0.5)
type(shortidentifier)
```
this raised the number of correct types to 100%.

As long as the Java AWT Robot internally is used, to type to the GUI, such situations can always happen, since internally there is no feedback possible about what really happens in the GUI.

... but since the beginning of Sikuli inserting short wait()s in problematic sections in most cases have made the workflows more robust.

**Comment by programmin1** [comment]
I wasn't sleeping long enough after each type character apparently.

It seems it also doesn't always work if you automate exporting a p12. I wonder if both these are related to a security issue they "fixed" ?: https://support.realvnc.com/Knowledgebase/Article/View/518/2/issue-with-keychain-access-on-mac-os-x-10111-el-capitan

**Comment by RaiMan** [comment]
what is

> exporting a p12.

**Comment by programmin1** [comment]
It's the option where you right click a key and click export, hit save, enter your password and generate a pkcs12 file.

**Comment by RaiMan** [comment]
ok, but that does not look special in any way.

... and 

> It seems it also doesn't always work

is not very specific about the symptoms and the point where it does not work anymore.

... and if it has something to do with the above mentioned quirk, then you cannot do anything with SikuliX anyway.
