### ISSUE TITLE
Please, create a 1.1.0 (or "stable") branch

### ISSUE THREAD

**Issue by UnitedMarsupials** [RaiMan/SikuliX-2014#208]
The master-branch comes with understandable warnings about instability, but the only alternative is using _pre-built_ JARs. People like myself, who wish to build stuff from source, have no obvious way of downloading the _stable_ source-code -- `origin/HEAD` is a moving target, but no other branches exist.

Please, create a "stable" branch, preferably with a version designation. For example, `1.1.1-alpha` would do... Thanks!

**Comment by RaiMan** [comment]
I understand your request.
... but the 1.1.x series is not in a shape to be built easily from sources.
This is mainly due to the pre-built native code, that cannot be simply built on the fly.

But if you want to give it a try, there is a target 1.1.0:
https://github.com/RaiMan/SikuliX-2014/releases

But be aware: even if you "build from sources", the generated jars are not useable without having run a setup (you might do this within the project context) or using it in a Maven project setup, that produces uber-jars. 

Version 2 will be more "normal" in this sense.

**Comment by RaiMan** [comment]
... nevertheless, when I decide the next days, that the 1.1.1 is final, then I will start the 1.1.2 bug fix release in a new branch.
