### ISSUE TITLE
Compile libVisionProxy for Windows

### ISSUE THREAD

**Issue by javierav** [RaiMan/SikuliX-2014#228]
Hi!

I made changes in `Libslux/src/main/resources/srcnativelibs/Vision/tessocr.cpp` file in order to fix an issue with the OCR. After that, I compiled the libVisionProxy.so for Linux using `runBuild` file, but I don't know how to build the equivalent version for Windows. Also I don't found more info in any documentation file. How can I do it?

Thanks.

**Comment by RaiMan** [comment]
Could you tell me more about why and what you fixed - just interested about ;-)

> build the equivalent version for Windows

For this I would have to dig down into my dark past (never did this again since 2013 ;-) with the risk, that I do not find anything about that anymore :-(

My approach in 2013:
- a setup with msys to compile and link everything including basic dependencies from the sources (today I would use [msys2](https://sourceforge.net/p/msys2/wiki/Home/), which might make it a bit easier, because more ready-to-use packages might be available)

As I remember, especially the Tesseract sources did not compile without errors, that needed some minor adjustments - but this might be not the case today.

With version 1.1.x I will not touch the native C++ code anymore.

With version 2 it is obsolete anyways, since I will use only ready-to-use packages on the Java level (OpenCV and Tess4J).

So simply: I cannot really help you in the details, since I cannot afford the effort to start allover again with this currently and until towards end of this year.

In the case, I find something helpful the next days, I will tell you.
