### ISSUE TITLE
Hello World example fails on Windows

### ISSUE THREAD

**Issue by svanteschubert** [RaiMan/SikuliX-2014#239]
The "Hello World" example for Windows (see http://sikulix-2014.readthedocs.io/en/latest/tutorials/helloworld/helloworld-win.html) does not work, as the first letter of type function, e.g. type("cmd") is being omitted. 

Strangely, paste works and type as well after paste.

PS: Is there a way to debug on our own?
PPS: Where are advanced examples, like testing Microsoft Office, where newcomers might take insights from. I found quite a few videos but close to zero example scripts. I am curious! :)

**Comment by RaiMan** [comment]
> as the first letter of type function, e.g. type("cmd") is being omitted.

Usually timing problems: add a short wait(0.3) before the type().

> Is there a way to debug on our own?

Debugging SikuliX scripts is a challenge. usually it is the best way to use the highlight feature, which visualizes the matches. 

> Where are advanced examples
In the net especially on youtube there are many examples. 

Generally there is no special situation with any kind of software, since everything is based on the pixels of images, that are shown on the screen by an application, then searched for by SikuliX and in most cases acted on with mouse and/or keyboard.

The challenge is to create a robust visual workflow, that drives the application exactly according to your intention.
