### ISSUE TITLE
IDE resolution is wrong on high-DPI displays

### ISSUE THREAD

**Issue by ldorigo** [RaiMan/SikuliX-2014#251]
Hey there,

Not sure how hard this might be to fix, but the interface is horribly pixelated on high-dpi monitors (it is on both retina macbooks I tried it on, so maybe it's only an issue with macbooks but I doubt it).

**Comment by RaiMan** [comment]
Yes, it is a Retina only problem (I am working on a Mac Book Pro Retina myself ;-).

Be sure to at least use the latest SikuliX version 1.1.1 and run at least Java 7.

Based on the explanation in your other question: You have to live with it.

A general workaround is to only use the SikuliX IDE to manage the images in modules and use e.g. PyCharmCE for scripting (with tons of additional features of a mature IDE) and import the image modules or use the image path feature. Of course then you will not see the images anymore inline in your code, but a good naming convention could help.

**Comment by ldorigo** [comment]
Thanks once more for the prompt reply :) 
You definitely have a billion more pressing things to do, but documenting how to do that (using Sikuli with pycharm) would be a big help - I've been trying for hours to make it work to no avail. The docs only detail the procedure with Eclipse and Netbeans, and I'm not used to python/jython development enough to figure out the equivalent. If I eventually manage to get it to work I can write down an explanation for future users.

(I could of course just download Eclipse but I'm used to Intellij IDE's , would be nice to have it work there).

**Comment by RaiMan** [comment]
Years ago I started with NetBeans (I never liked Eclipse ;-). Last year I switched to IntelliJ and I am very satisfied with my decision.

PyCharm is really a good IDE for Python especially when you are used to the IntelliJ stuff.

Since I am currently busy with the basic implementation of script running in version 2, I will take the chance to write down the steps, to get PyCharm working with SikuliX.

For you and now the initial steps (assuming you are familiar with the IntelliJ basics):
 - install jython, so it can be run from command line (on Mac I recommend to use homebrew to get it: simply: brew install jython), but you might also use the installer from the jython homepage.
 - check on a command line that it works: jython
 - in PyCharms in the default settings (Preferences) in the Project Interpreter section activate Jython as interpreter (add local and navigate to /usr/local/bin/jython)

the following steps are needed for every project:
 - create a new project and take care, that jython is selected as interpreter
 - add at least one .py file (here test.py with one line print "hello")
 - goto EditConfigurations and add a new Python config, again take care that Jython is the Interpreter
 - (for the first project ever, you should now run this config and should get the printout hello)
 - in the config edit the environment variables and add an entry as
```
CLASSPATH <path-to-sikulixapi.jar>
```
 - save the config with OK
 - in your test script add the lines
```
import org.sikuli.script.SikulixForJython
from sikuli import *
popup("Hello from SikuliX")
```
 - again run your config - you should get the popup 

These are only the basics: to get rid off the errors about not found SikuliX features some more has to be done (but it is the same as with Eclipse PyDev).

I simply switched these error messages off ;-)
