### ISSUE TITLE
Possibility to fold code in the IDE

### ISSUE THREAD

**Issue by ldorigo** [RaiMan/SikuliX-2014#252]
Hi!

I love the IDE (seeing snapshots inline is great), but there should be some way to fold functions. Long files are unreadable at the moment :-) (Especially since the resolution is so low, see previously opened issue).

**Comment by RaiMan** [comment]
Since the Sikuli IDE is a nearly 8 years old artefact on the Java Swing/AWT level 1.6 created from base by the former developers, that is not really prepared to get enhancements easily, I decided, to freeze the features in the version 1 line 3 years ago: to much effort.

So no, there will not be any enhancements in this direction.

If you have problems with huge scripts, then best practice is to divide it into smaller peaces (modules) and use the import feature based on classes/functions (see: http://sikulix-2014.readthedocs.io/en/latest/scripting.html#importing-other-sikuli-scripts-reuse-code-and-images) and/or use the run feature to run a module from another one (see: http://sikulix-2014.readthedocs.io/en/latest/scripting.html#running-scripts-and-snippets-from-within-other-scripts-and-run-scripts-one-after-the-other)

Version 2 will support different existing mature editors together with an external image tool. A few of these editors (e.g. jEdit) will get the "show the images in the script" as a plugin.

**Comment by ldorigo** [comment]
Thanks for the prompt reply. Looking forward to the new version.
